app/main/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed

from wtforms import StringField, TextAreaField, SubmitField
from wtforms.validators import Length

from app import images

class EditProfileForm(FlaskForm):
    profile_pic = FileField(
        'Profile Pic',
        validators=[
            FileAllowed(images)
        ]
    )
    displayed_name = StringField(
        'Displayed Name',
        validators=[Length(0,128)]
    )
    status_message = TextAreaField(
        'Status Message',
        validators=[Length(0,128)]
    )
    submit = SubmitField('Save')


class PostForm(FlaskForm):
    body = TextAreaField(
        'Post Something',
        validators=[Length(1)]
    )
    submit = SubmitField('Post!')

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes

app/main/routes.py
import os
from datetime import datetime

from flask import render_template, redirect, request, flash, url_for, current_app, g
from flask_login import login_required, current_user
from flask_babel import get_locale

from app import db, images
from app.models import User, Post
from app.main import bp
from app.main.forms import EditProfileForm, PostForm

from werkzeug.utils import secure_filename

@bp.before_request
def before_request():
    if current_user.is_authenticated:
        current_user.last_seen = datetime.utcnow()
        db.session.commit()
    g.locale = str(get_locale())

@bp.route('/')
@bp.route('/index')
def index():

    if current_user.is_authenticated:
        posts = Post.query.order_by(Post.timestamp.desc())
        return render_template(
            'main/index.html.j2',
            title=f'PiBoard ({current_user.displayed_name or current_user.handle})',
            posts=posts
        )
    return render_template(
        'main/index.html.j2',
        title='PiBoard'
    )

@bp.route('/post/delete/<post_id>', methods=['GET'])
@login_required
def delete_post(post_id):
    to_delete = Post.query.filter_by(id=post_id).first_or_404()
    if current_user.handle != to_delete.author.handle:
        flash('You cannot delete other peoples posts.')
        return redirect(url_for('main.index'))

    Post.query.filter_by(id=post_id).delete()
    db.session.commit()
    flash('Post deleted.')
    return redirect(url_for('main.index'))


@bp.route('/post/<post_id>', methods=['GET', 'POST'])
@login_required
def edit_post(post_id):
    post = Post.query.filter_by(id=post_id).first_or_404()
    user = post.author

    if post.author.handle != current_user.handle:
        flash('You cannot edit other users posts.')
        return redirect(
            url_for(
                'main.post',
                handle=post.author.handle,
                post_id=post.id
            )
        )

    form = PostForm()
    if form.validate_on_submit():
        post.body = form.body.data
        post.edited = datetime.utcnow()
        db.session.commit()
        flash('Your post has been edited.')
        return redirect(
            url_for(
                'main.post',
                handle=post.author.handle,
                post_id=post.id
            )
        )
    elif request.method == 'GET':
        form.body.data = post.body

    return render_template(
        'main/post.html.j2',
        title='Edit Post',
        comment_form=form,
        user=user,
        post=post
    )


@bp.route('/post/<handle>/<post_id>', methods=['GET', 'POST'])
@login_required
def post(handle, post_id):
    post = Post.query.filter_by(id=post_id).first_or_404()
    user = User.query.filter_by(handle=handle).first_or_404()

    comment_form = PostForm()
    if comment_form.validate_on_submit():
        comment = Post(
            body=comment_form.body.data,
            author=current_user,
            comment_to=post
        )
        db.session.add(comment)
        db.session.commit()
        return redirect(
            url_for(
                'main.post',
                handle=handle,
                post_id=post_id
            )
        )

    return render_template(
        'main/post.html.j2',
        user=user,
        post=post,
        title=f'Answer {user.displayed_name or user.handle}',
        comment_form=comment_form
    )


@bp.route('/profile/<handle>', methods=['GET', 'POST'])
@login_required
def profile(handle):
    user = User.query.filter_by(handle=handle).first_or_404()
    posts = user.posts.order_by(Post.timestamp.desc()).all()

    post_form = PostForm()

    if post_form.validate_on_submit():
        post = Post(
            body=post_form.body.data,
            author=current_user
        )
        db.session.add(post)
        db.session.commit()
        flash('Your post has been posted')
        return redirect(url_for('main.profile', handle=handle))

    return render_template(
        'main/user_posts.html.j2',
        title=f'User {user.handle}',
        user=user,
        posts=posts,
        post_form=post_form,
        owner=(current_user.handle == handle)
    )


@bp.route('/edit_profile/<handle>', methods=['GET', 'POST'])
@login_required
def edit_profile(handle):
    if current_user.handle != handle:
        flash('You cannot edit the profile of someone else!')
        return redirect(url_for('main.profile', handle=handle))

    user = User.query.filter_by(handle=handle).first_or_404()
    form = EditProfileForm()
    if form.validate_on_submit():
        new_profile_pic = form.profile_pic.data \
            if form.profile_pic.data else None
        if new_profile_pic:
            print(handle, secure_filename(new_profile_pic.filename))
            filename = images.save(
                new_profile_pic,
                handle,
                secure_filename(new_profile_pic.filename.lower())
            )

            old_profile_pic = user.profile_pic
            user.profile_pic = filename

            try:
                os.remove(images.path(old_profile_pic))
            except:
                pass

        new_displayed_name = form.displayed_name.data \
            if form.displayed_name.data else None
        if new_displayed_name != user.displayed_name:
            user.displayed_name = new_displayed_name
            flash(f'Displayed name changed to {current_user.displayed_name}!')

        new_status_message = form.status_message.data \
            if form.status_message.data else None
        if new_status_message != user.status_message:
            user.status_message = new_status_message
            flash(f'Status message updated!')

        db.session.commit()
        return redirect(url_for('main.profile', handle=handle))

    elif request.method == 'GET':
        form.displayed_name.data = current_user.displayed_name
        form.status_message.data = current_user.status_message

    return render_template(
        'main/edit_profile.html.j2',
        title='Edit Profile',
        user=user,
        form=form
    )

app/templates/main/_delete_post_dialog.html.j2
<div class="modal fade" id="delete-post-{{ post.id }}" tabindex="-1"
     role="dialog" aria-labelledby="delete-post-{{ post.id }}-label" aria-hidden="true">
  <div class="modal-dialog modal-sm" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" align="center" id="delete-post-{{ post.id }}-label">Are you sure?</h5>
      </div>
      <div class="modal-body">
        Do you really want to delete this post?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-xs btn-secondary" data-dismiss="modal">No</button>
        <a href="{{ url_for('main.delete_post', post_id=post.id) }}" class="btn btn-xs btn-danger">Yes</a>
      </div>
    </div>
  </div>
</div>

app/templates/main/_post.html.j2
<div class="post">
  <div class="main-row row">
    <div class="post-avatar col-xs-3 col-md-1">
      <a href="{{ url_for('main.profile', handle=post.author.handle) }}">
        <img src="{{ image_url(post.author.profile_pic) }}" class="float-left">
      </a>
    </div>
    <div class="post-main col-xs-9 col-md-11">
      <div class="row">
        <div class="col-xs-6 col-md-6">
          {% if post.author.displayed_name %}
          <b>{{ post.author.displayed_name }}</b>
          <i>({{ post.author.handle }})</i>
          {% else %}
          <b>{{ post.author.handle }}</b>
          {% endif %}
        </div>
        <div class="col-xs-6 col-md-6" align="right">
          {% if post.edited %}
          Edited: {{ moment(post.edited).fromNow() }}
          {% else %}
          {{ moment(post.timestamp).fromNow() }}
          {% endif %}
        </div>
      </div>
      <div class="row">
        <div class="col-xs-12 col-md-12">
          {{ post.body }}
        </div>
      </div>
    </div>
  </div>
  <div class="nav-row row">
    <div class="col-xs-3 col-md-1">
    </div>
    <div class="post-nav col-xs-9 col-md-11">
      <a class="post-btn btn btn-xs btn-default"
         href="{{ url_for('main.post', handle=post.author.handle, post_id=post.id) }}">
        Show
      </a>
      {% if post.comment_to and not top_level_visible %}
      <a class="post-btn btn btn-xs btn-default"
         href="{{ url_for('main.post', handle=post.comment_to.author.handle, post_id=post.comment_to.id)}}">
        Parent
      </a>
      {% endif %}
      {% if post.author.handle == current_user.handle %}
      <a class="post-btn btn btn-xs btn-default"
         href="{{ url_for('main.edit_post', post_id=post.id) }}">
        Edit
      </a>
      <button type="button" class="post-btn btn btn-xs btn-default" data-toggle="modal" data-target="#delete-post-{{ post.id }}">
        Delete
      </button>
      {% include "main/_delete_post_dialog.html.j2" %}
      {% endif %}
    </div>
  </div>
  <div class="answer-row row">
    <div class="col-xs-2 col-sd-1 col-md-1"></div>
    <div class="post-answers col-xs-10 col-sd-11 col-md-11">
    {% if show_answers and depth < MAX_DEPTH %}
      <p>Answers</p>
      {% if post.comments %}
        {% with depth = depth+1 %}
          {% for post in post.comments %}
            <p>{% include "main/_post.html.j2" %}</p>
          {% endfor %}
        {% endwith %}
      {% endif %}
    {% else %}
      {% with answers = len(post.comments) %}
      {% if answers == 0 %}
        No answers
      {% elif answers == 1 %}
        1 answer
      {% else %}
        {{ answers }} answers
      {% endif %}
      {% endwith %}
    {% endif %}
    </div>
  </div>
</div>

app/templates/main/_welcome.html.j2
<h1>Welcome to PiBoard</h1>
<p>
  This is PiBoard, the <b>little</b> bulletin board for your intranet.
</p>
<p>
  If you are a new user, you may want to
  <a href="{{ url_for('auth.register') }}">register</a>.
  If you already did that, you may want to
  <a href="{{ url_for('auth.login') }}">login</a>.
</p>

app/templates/main/edit_profile.html.j2
{% extends "main/profile.html.j2" %}

{% block profile_content %}
<h1>Edit Profile</h1>
    <div class="row">
      <div class="col-md-9">
        {{ wtf.quick_form(form) }}
      </div>
    </div>
{% endblock profile_content %}

app/templates/main/index.html.j2
{% extends "base.html.j2" %}

{% block app_content %}
{% if current_user.is_anonymous %}
  {% include 'main/_welcome.html.j2' %}
{% else %}
  <div class="row">
    <div class="col-xs-3 col-md-2" align="center">
      <img src="https://i.stack.imgur.com/W08Uq.png" style="width=100%; max-width: 100%">
    </div>
    <div class="col-xs-9 col-md-10">
      {% with top_level_visible = True, show_answers = False, depth = 0 %}
      {% for post in posts %}
        {% if not post.parent_id %}
        <p>{% include "main/_post.html.j2" %}</p>
        <hr id="post-separator">
        {% endif %}
      {% endfor %}
      {% endwith %}
    </div>
  </div>
{% endif %}
{% endblock app_content %}

app/templates/main/post.html.j2
{% extends 'main/profile.html.j2' %}

{% block profile_content %}
  <div class="row">
    <div class="col-md-12">
      {{ wtf.quick_form(comment_form) }}
    </div>
  </div>
  {% with top_level_visible = not post.comment_to, show_answers = True, depth = 0 %}
  <div class="row">
    <div class="col-md-12">
      <p>{% include 'main/_post.html.j2' %}</p>
    </div>
  </div>
  {% endwith %}
{% endblock profile_content %}

app/templates/main/profile.html.j2
{% extends 'base.html.j2' %}

{% block app_content %}
<div class="row">
  <div class="col-md-2">
    {% if user.profile_pic %}
    <div class="profile_pic">
      <img src="{{ image_url(user.profile_pic) }}">
    </div>
    {% endif %}
    {% if user.displayed_name %}
    <h2>{{ user.displayed_name }}</h2>
    <p>{{ user.handle }}</p>
    {% else %}
    <h2>{{ user.handle }}</h2>
    {% endif %}
    <hr>
    <p>{{ user.email }}</p>
    {% if user.last_seen %}
    <p>
      <b>Last seen</b> {{ moment(user.last_seen).fromNow() }}
    </p>
    {% endif %}
    {% if user.status_message %}
    <p>
      <b>Status:</b><br>
      {{ user.status_message }}
    </p>
    {% endif %}
    {% if user.handle == current_user.handle %}
    <a href="{{ url_for('main.edit_profile', handle=user.handle) }}">Edit Profile</a>
    {% endif %}
  </div>
  <div class="col-md-10">
    {% block profile_content %}
    {% endblock profile_content %}
  </div>
</div>
{% endblock app_content %}

app/templates/main/user_posts.html.j2
{% extends "main/profile.html.j2" %}

{% block profile_content %}
  {% if owner %}
  <div class="row">
    <div class="col-md-12">
      {{ wtf.quick_form(post_form) }}
    </div>
  </div>
  {% endif %}
  <div class="row">
    <div class="col-md-12">
      {% with top_level_visible = True, show_answers = False, depth = 0 %}
      {% for post in posts %}
        {% if not post.parent_id %}
        <p>{% include "main/_post.html.j2" %}</p>
        <hr id="post-separator">
        {% endif %}
      {% endfor %}
      {% endwith %}
    </div>
  </div>
{% endblock profile_content %}